"use client";

import { FormEvent, useEffect, useState } from "react";

type Profile = { city?: string | null; state?: string | null; profession?: string | null; objective?: string | null; desiredRoles?: string | null; experienceSummary?: string | null; educationSummary?: string | null; skills?: string | null; availability?: string | null; preferences?: string | null };
type Preferences = { desiredLocations: string; jobTypes: string; salary: string; courses: string; certificates: string };
type Resume = { id: string; name: string; mimeType: string; version: number; approved: boolean; active: boolean; createdAt: string };
type Application = { id: string; company: string; role: string; platform: string; status: string; externalUrl?: string | null; createdAt: string };
type Integration = { platform: "LINKEDIN" | "GUPY"; status: "DISCONNECTED" | "ACTION_REQUIRED" | "CONNECTED" | "ERROR"; connectedAt?: string | null };
const emptyProfile: Profile = { city: "", state: "RJ", profession: "", objective: "", desiredRoles: "", skills: "", availability: "Qualquer turno" };
const emptyPreferences: Preferences = { desiredLocations: "", jobTypes: "CLT, efetivo", salary: "", courses: "", certificates: "" };

export default function DashboardClient() {
  const [profile, setProfile] = useState<Profile>(emptyProfile);
  const [resumes, setResumes] = useState<Resume[]>([]);
  const [applications, setApplications] = useState<Application[]>([]);
  const [integrations, setIntegrations] = useState<Integration[]>([]);
  const [message, setMessage] = useState("");
  const [loading, setLoading] = useState(true);
  const [preferences, setPreferences] = useState<Preferences>(emptyPreferences);
  const [searchRole, setSearchRole] = useState("");
  const [searchLocation, setSearchLocation] = useState("Rio de Janeiro");
  useEffect(() => { if (!window.location.hash || window.location.hash === "#inicio") { window.history.replaceState(null, "", "#perfil"); document.getElementById("perfil")?.scrollIntoView(); } }, [loading]);
  async function refresh() {
    const [p, r, a, i] = await Promise.all([fetch("/api/profile"), fetch("/api/resumes"), fetch("/api/applications"), fetch("/api/integrations")]);
    if ([p, r, a, i].some(response => response.status === 401)) { setMessage("Entre com sua conta para salvar seus dados."); setLoading(false); return; }
    const [pd, rd, ad, id] = await Promise.all([p.json(), r.json(), a.json(), i.json()]);
    const loadedProfile = { ...emptyProfile, ...(pd.profile ?? {}) }; setProfile(loadedProfile);
    if (loadedProfile.preferences) { try { setPreferences({ ...emptyPreferences, ...JSON.parse(loadedProfile.preferences) }); } catch { setPreferences({ ...emptyPreferences, jobTypes: loadedProfile.preferences }); } }
    setResumes(rd.resumes ?? []); setApplications(ad.applications ?? []); setIntegrations(id.integrations ?? []); setLoading(false);
  }
  useEffect(() => { refresh().catch(() => { setMessage("Não foi possível carregar seus dados agora."); setLoading(false); }); }, []);
  async function saveProfile(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setMessage("Salvando perfil..."); const response = await fetch("/api/profile", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...profile, preferences: JSON.stringify(preferences) }) }); setMessage(response.ok ? "Perfil completo salvo com sucesso. Agora envie seu currículo." : "Não foi possível salvar o perfil."); if (response.ok) window.location.hash = "curriculo"; }
  async function uploadResume(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setMessage("Enviando currículo..."); const form = event.currentTarget; const response = await fetch("/api/resumes", { method: "POST", body: new FormData(form) }); const data = await response.json().catch(() => ({})); setMessage(response.ok ? "Currículo enviado e definido como principal." : data.error ?? "Falha no envio."); if (response.ok) { form.reset(); await refresh(); } }
  async function addApplication(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setMessage("Registrando candidatura..."); const form = event.currentTarget; const payload = Object.fromEntries(new FormData(form)); const response = await fetch("/api/applications", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json().catch(() => ({})); setMessage(response.ok ? "Candidatura registrada." : data.error ?? "Falha ao registrar."); if (response.ok) { form.reset(); await refresh(); } }
  async function updateStatus(id: string, status: string) { const response = await fetch(`/api/applications/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status }) }); if (response.ok) await refresh(); else setMessage("Não foi possível atualizar o status."); }
  async function setIntegration(platform: "LINKEDIN" | "GUPY", connected: boolean) { setMessage(connected ? `Salvando conexão com ${platform}...` : `Desconectando ${platform}...`); const response = await fetch("/api/integrations", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ platform, connected }) }); setMessage(response.ok ? (connected ? `${platform} marcado como conectado nesta conta.` : `${platform} desconectado.`) : "Não foi possível salvar a conexão."); if (response.ok) await refresh(); }
  const integrationStatus = (platform: "LINKEDIN" | "GUPY") => integrations.find(item => item.platform === platform)?.status === "CONNECTED";
  if (loading) return <section className="workspace-card"><p>Carregando seu ambiente...</p></section>;
  return <>
    {message && <div className="notice" role="status">{message}</div>}
    <section className="workspace-card onboarding-card" id="perfil"><div className="section-heading"><div><span className="eyebrow">PRIMEIRO PASSO</span><h2>Crie seu perfil profissional</h2></div><span>Salvo somente na sua conta</span></div><p className="section-copy">Preencha as informações abaixo. Elas serão usadas para encontrar vagas compatíveis e preparar suas candidaturas.</p>
      <form className="form-grid" onSubmit={saveProfile}>
        <fieldset className="wide"><legend>Dados profissionais</legend><div className="fieldset-grid"><label>Profissão atual<input required value={profile.profession ?? ""} onChange={e => setProfile({ ...profile, profession: e.target.value })} placeholder="Ex.: Técnico em Mecânica" /></label><label>Cidade atual<input required value={profile.city ?? ""} onChange={e => setProfile({ ...profile, city: e.target.value })} placeholder="Sua cidade" /></label><label>Estado<input required value={profile.state ?? ""} onChange={e => setProfile({ ...profile, state: e.target.value.toUpperCase() })} maxLength={2} /></label><label className="span-2">Cargos desejados<input required value={profile.desiredRoles ?? ""} onChange={e => setProfile({ ...profile, desiredRoles: e.target.value })} placeholder="Técnico em Mecânica, Auxiliar de Mecânico, Operador de Máquinas" /></label></div></fieldset>
        <fieldset className="wide"><legend>Objetivo e experiência</legend><div className="fieldset-grid"><label className="span-2">Objetivo profissional<textarea required value={profile.objective ?? ""} onChange={e => setProfile({ ...profile, objective: e.target.value })} rows={3} placeholder="Descreva a oportunidade que procura" /></label><label className="span-2">Experiências profissionais<textarea value={profile.experienceSummary ?? ""} onChange={e => setProfile({ ...profile, experienceSummary: e.target.value })} rows={5} placeholder="Empresa, cargo, período e principais atividades" /></label></div></fieldset>
        <fieldset className="wide"><legend>Formação, cursos e certificações</legend><div className="fieldset-grid"><label className="span-2">Formação acadêmica<textarea value={profile.educationSummary ?? ""} onChange={e => setProfile({ ...profile, educationSummary: e.target.value })} rows={3} placeholder="Curso, instituição, situação e período" /></label><label>Cursos complementares<textarea value={preferences.courses} onChange={e => setPreferences({ ...preferences, courses: e.target.value })} rows={4} placeholder="Nome do curso, instituição e carga horária" /></label><label>Certificações<textarea value={preferences.certificates} onChange={e => setPreferences({ ...preferences, certificates: e.target.value })} rows={4} placeholder="Certificação, emissor e validade" /></label></div></fieldset>
        <fieldset className="wide"><legend>Competências e preferências de vaga</legend><div className="fieldset-grid"><label className="span-2">Competências<textarea required value={profile.skills ?? ""} onChange={e => setProfile({ ...profile, skills: e.target.value })} rows={3} placeholder="Mecânica, manutenção preventiva, leitura de desenhos..." /></label><label>Localizações desejadas<input value={preferences.desiredLocations} onChange={e => setPreferences({ ...preferences, desiredLocations: e.target.value })} placeholder="Rio de Janeiro, Duque de Caxias..." /></label><label>Tipos de vaga<input value={preferences.jobTypes} onChange={e => setPreferences({ ...preferences, jobTypes: e.target.value })} placeholder="CLT, temporário, estágio" /></label><label>Faixa salarial desejada<input value={preferences.salary} onChange={e => setPreferences({ ...preferences, salary: e.target.value })} placeholder="Ex.: a partir de R$ 2.000" /></label><label>Disponibilidade<input required value={profile.availability ?? ""} onChange={e => setProfile({ ...profile, availability: e.target.value })} placeholder="Turnos, início e viagens" /></label></div></fieldset>
        <div className="form-footer wide"><span>Você poderá alterar tudo depois.</span><button className="primary-button" type="submit">Salvar perfil e continuar</button></div>
      </form></section>
    <section className="workspace-card" id="curriculo"><div className="section-heading"><div><span className="eyebrow">DOCUMENTOS</span><h2>Meus currículos</h2></div><span>{resumes.length} arquivo(s)</span></div><form className="upload-row" onSubmit={uploadResume}><label>Nome<input name="name" required placeholder="Currículo Técnico" /></label><label>PDF ou Word<input name="file" type="file" accept=".pdf,.doc,.docx" required /></label><button className="primary-button" type="submit">Enviar currículo</button></form><div className="record-list">{resumes.length ? resumes.map(resume => <div className="record" key={resume.id}><div><strong>{resume.name}</strong><small>Versão {resume.version} · {resume.mimeType}</small></div><span className={resume.approved ? "pill success" : "pill"}>{resume.approved ? "Principal aprovado" : "Em revisão"}</span></div>) : <p className="empty">Nenhum currículo enviado ainda.</p>}</div></section>

    <section className="workspace-card" id="vagas"><div className="section-heading"><div><span className="eyebrow">BUSCA ASSISTIDA</span><h2>Procurar vagas compatíveis</h2></div><span>LinkedIn + Gupy</span></div><p className="section-copy">Informe o cargo e a localização. A busca abre os resultados atuais de cada plataforma; depois você pode registrar aqui as vagas escolhidas.</p><div className="search-form"><label>Cargo ou palavra-chave<input value={searchRole} onChange={e => setSearchRole(e.target.value)} placeholder={profile.desiredRoles || "Técnico em Mecânica"} /></label><label>Localização<input value={searchLocation} onChange={e => setSearchLocation(e.target.value)} /></label></div><div className="search-actions"><a className={`primary-button link-button ${!(searchRole || profile.desiredRoles) ? "disabled" : ""}`} href={`https://www.linkedin.com/jobs/search/?keywords=${encodeURIComponent(searchRole || profile.desiredRoles || "")}&location=${encodeURIComponent(searchLocation)}`} target="_blank" rel="noreferrer">Buscar no LinkedIn</a><a className={`secondary-button ${!(searchRole || profile.desiredRoles) ? "disabled" : ""}`} href={`https://portal.gupy.io/job-search/term=${encodeURIComponent(searchRole || profile.desiredRoles || "")}`} target="_blank" rel="noreferrer">Buscar na Gupy</a></div>{!(searchRole || profile.desiredRoles) && <p className="helper">Preencha um cargo aqui ou salve seus cargos desejados no perfil.</p>}</section>

    <section className="workspace-card" id="integracoes"><div className="section-heading"><div><span className="eyebrow">CONTAS EXTERNAS</span><h2>LinkedIn e Gupy</h2></div><span>Login individual</span></div><p className="section-copy">Abra cada plataforma, faça o login na nova aba e volte aqui para confirmar. O status fica salvo na sua conta; sua senha e a sessão continuam protegidas no navegador.</p><div className="integration-grid"><article><div className="integration-logo linkedin">in</div><div><strong>LinkedIn</strong><small>{integrationStatus("LINKEDIN") ? "Conexão confirmada" : "Aguardando confirmação"}</small></div><div className="integration-controls"><a href="https://www.linkedin.com/login" target="_blank" rel="noreferrer">1. Abrir LinkedIn</a><button className={integrationStatus("LINKEDIN") ? "connected-button" : "confirm-button"} onClick={() => setIntegration("LINKEDIN", !integrationStatus("LINKEDIN"))}>{integrationStatus("LINKEDIN") ? "Desconectar" : "2. Já entrei"}</button></div></article><article><div className="integration-logo gupy">G</div><div><strong>Gupy</strong><small>{integrationStatus("GUPY") ? "Conexão confirmada" : "Aguardando confirmação"}</small></div><div className="integration-controls"><a href="https://login.gupy.io/candidates/signin" target="_blank" rel="noreferrer">1. Abrir Gupy</a><button className={integrationStatus("GUPY") ? "connected-button" : "confirm-button"} onClick={() => setIntegration("GUPY", !integrationStatus("GUPY"))}>{integrationStatus("GUPY") ? "Desconectar" : "2. Já entrei"}</button></div></article></div><p className="helper">Uma conexão confirmada indica que você concluiu o login naquela plataforma. Se a sessão externa expirar, abra a plataforma e entre novamente.</p></section>

    <section className="workspace-card" id="candidaturas"><div className="section-heading"><div><span className="eyebrow">ACOMPANHAMENTO</span><h2>Minhas candidaturas</h2></div><span>{applications.length} registrada(s)</span></div><form className="application-form" onSubmit={addApplication}><input name="company" required placeholder="Empresa" /><input name="role" required placeholder="Cargo" /><select name="platform" defaultValue="LINKEDIN"><option>LINKEDIN</option><option>GUPY</option><option>OUTRO</option></select><input name="externalUrl" type="url" placeholder="Link (opcional)" /><button className="primary-button" type="submit">Registrar</button></form><div className="record-list" id="historico">{applications.length ? applications.map(item => <div className="record application-record" key={item.id}><div className="company-logo">{item.company[0]}</div><div><strong>{item.role}</strong><small>{item.company} · {item.platform}</small></div><select aria-label={`Status de ${item.role}`} value={item.status} onChange={e => updateStatus(item.id, e.target.value)}><option value="DRAFT">Rascunho</option><option value="SENT">Enviada</option><option value="IN_REVIEW">Em análise</option><option value="INTERVIEW">Entrevista</option><option value="REJECTED">Encerrada</option></select>{item.externalUrl && <a href={item.externalUrl} target="_blank" rel="noreferrer">Abrir vaga</a>}</div>) : <p className="empty">Registre sua primeira candidatura para acompanhar o processo.</p>}</div></section>

    <section className="workspace-card" id="configuracoes"><div className="section-heading"><div><span className="eyebrow">SUA CONTA</span><h2>Configurações</h2></div></div><div className="settings-grid"><div><strong>Dados profissionais</strong><p>Atualize profissão, objetivos, competências e disponibilidade.</p><a href="#perfil">Editar perfil</a></div><div><strong>Currículo principal</strong><p>Envie a versão que será usada nas candidaturas.</p><a href="#curriculo">Gerenciar currículos</a></div><div><strong>Plataformas</strong><p>Abra suas contas individuais do LinkedIn e da Gupy.</p><a href="#integracoes">Configurar conexões</a></div></div></section>

    <section className="privacy-card" id="privacidade"><strong>Privacidade e isolamento</strong><p>Todos os registros são associados à identidade da conta conectada. O sistema não aceita um identificador de usuário enviado pela tela para acessar dados de outra pessoa.</p></section>
  </>;
}
