"use client";

import { FormEvent, useEffect, useState } from "react";

type Profile = { city?: string | null; state?: string | null; profession?: string | null; objective?: string | null; desiredRoles?: string | null; skills?: string | null; availability?: string | null };
type Resume = { id: string; name: string; mimeType: string; version: number; approved: boolean; active: boolean; createdAt: string };
type Application = { id: string; company: string; role: string; platform: string; status: string; externalUrl?: string | null; createdAt: string };
const emptyProfile: Profile = { city: "", state: "RJ", profession: "", objective: "", desiredRoles: "", skills: "", availability: "Qualquer turno" };

export default function DashboardClient() {
  const [profile, setProfile] = useState<Profile>(emptyProfile);
  const [resumes, setResumes] = useState<Resume[]>([]);
  const [applications, setApplications] = useState<Application[]>([]);
  const [message, setMessage] = useState("");
  const [loading, setLoading] = useState(true);
  const [searchRole, setSearchRole] = useState("");
  const [searchLocation, setSearchLocation] = useState("Rio de Janeiro");
  async function refresh() {
    const [p, r, a] = await Promise.all([fetch("/api/profile"), fetch("/api/resumes"), fetch("/api/applications")]);
    if ([p, r, a].some(response => response.status === 401)) { setMessage("Entre com sua conta para salvar seus dados."); setLoading(false); return; }
    const [pd, rd, ad] = await Promise.all([p.json(), r.json(), a.json()]);
    setProfile({ ...emptyProfile, ...(pd.profile ?? {}) }); setResumes(rd.resumes ?? []); setApplications(ad.applications ?? []); setLoading(false);
  }
  useEffect(() => { refresh().catch(() => { setMessage("Não foi possível carregar seus dados agora."); setLoading(false); }); }, []);
  async function saveProfile(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setMessage("Salvando perfil..."); const response = await fetch("/api/profile", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(profile) }); setMessage(response.ok ? "Perfil salvo com sucesso." : "Não foi possível salvar o perfil."); }
  async function uploadResume(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setMessage("Enviando currículo..."); const form = event.currentTarget; const response = await fetch("/api/resumes", { method: "POST", body: new FormData(form) }); const data = await response.json().catch(() => ({})); setMessage(response.ok ? "Currículo enviado e definido como principal." : data.error ?? "Falha no envio."); if (response.ok) { form.reset(); await refresh(); } }
  async function addApplication(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setMessage("Registrando candidatura..."); const form = event.currentTarget; const payload = Object.fromEntries(new FormData(form)); const response = await fetch("/api/applications", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json().catch(() => ({})); setMessage(response.ok ? "Candidatura registrada." : data.error ?? "Falha ao registrar."); if (response.ok) { form.reset(); await refresh(); } }
  async function updateStatus(id: string, status: string) { const response = await fetch(`/api/applications/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status }) }); if (response.ok) await refresh(); else setMessage("Não foi possível atualizar o status."); }
  if (loading) return <section className="workspace-card"><p>Carregando seu ambiente...</p></section>;
  return <>
    {message && <div className="notice" role="status">{message}</div>}
    <section className="workspace-card" id="perfil"><div className="section-heading"><div><span className="eyebrow">SEUS DADOS</span><h2>Perfil profissional</h2></div><span>Salvo na sua conta</span></div>
      <form className="form-grid" onSubmit={saveProfile}>
        <label>Profissão atual<input value={profile.profession ?? ""} onChange={e => setProfile({ ...profile, profession: e.target.value })} placeholder="Ex.: Técnico em Mecânica" /></label><label>Cidade<input value={profile.city ?? ""} onChange={e => setProfile({ ...profile, city: e.target.value })} placeholder="Sua cidade" /></label><label>Estado<input value={profile.state ?? ""} onChange={e => setProfile({ ...profile, state: e.target.value })} maxLength={2} /></label>
        <label className="wide">Cargos desejados<input value={profile.desiredRoles ?? ""} onChange={e => setProfile({ ...profile, desiredRoles: e.target.value })} placeholder="Separe por vírgula" /></label><label className="wide">Objetivo profissional<textarea value={profile.objective ?? ""} onChange={e => setProfile({ ...profile, objective: e.target.value })} rows={3} /></label><label className="wide">Competências<textarea value={profile.skills ?? ""} onChange={e => setProfile({ ...profile, skills: e.target.value })} rows={3} /></label><label className="wide">Disponibilidade<input value={profile.availability ?? ""} onChange={e => setProfile({ ...profile, availability: e.target.value })} /></label><button className="primary-button" type="submit">Salvar perfil</button>
      </form></section>
    <section className="workspace-card" id="curriculo"><div className="section-heading"><div><span className="eyebrow">DOCUMENTOS</span><h2>Meus currículos</h2></div><span>{resumes.length} arquivo(s)</span></div><form className="upload-row" onSubmit={uploadResume}><label>Nome<input name="name" required placeholder="Currículo Técnico" /></label><label>PDF ou Word<input name="file" type="file" accept=".pdf,.doc,.docx" required /></label><button className="primary-button" type="submit">Enviar currículo</button></form><div className="record-list">{resumes.length ? resumes.map(resume => <div className="record" key={resume.id}><div><strong>{resume.name}</strong><small>Versão {resume.version} · {resume.mimeType}</small></div><span className={resume.approved ? "pill success" : "pill"}>{resume.approved ? "Principal aprovado" : "Em revisão"}</span></div>) : <p className="empty">Nenhum currículo enviado ainda.</p>}</div></section>

    <section className="workspace-card" id="vagas"><div className="section-heading"><div><span className="eyebrow">BUSCA ASSISTIDA</span><h2>Procurar vagas compatíveis</h2></div><span>LinkedIn + Gupy</span></div><p className="section-copy">Informe o cargo e a localização. A busca abre os resultados atuais de cada plataforma; depois você pode registrar aqui as vagas escolhidas.</p><div className="search-form"><label>Cargo ou palavra-chave<input value={searchRole} onChange={e => setSearchRole(e.target.value)} placeholder={profile.desiredRoles || "Técnico em Mecânica"} /></label><label>Localização<input value={searchLocation} onChange={e => setSearchLocation(e.target.value)} /></label></div><div className="search-actions"><a className={`primary-button link-button ${!(searchRole || profile.desiredRoles) ? "disabled" : ""}`} href={`https://www.linkedin.com/jobs/search/?keywords=${encodeURIComponent(searchRole || profile.desiredRoles || "")}&location=${encodeURIComponent(searchLocation)}`} target="_blank" rel="noreferrer">Buscar no LinkedIn</a><a className={`secondary-button ${!(searchRole || profile.desiredRoles) ? "disabled" : ""}`} href={`https://portal.gupy.io/job-search/term=${encodeURIComponent(searchRole || profile.desiredRoles || "")}`} target="_blank" rel="noreferrer">Buscar na Gupy</a></div>{!(searchRole || profile.desiredRoles) && <p className="helper">Preencha um cargo aqui ou salve seus cargos desejados no perfil.</p>}</section>

    <section className="workspace-card" id="integracoes"><div className="section-heading"><div><span className="eyebrow">CONTAS EXTERNAS</span><h2>LinkedIn e Gupy</h2></div><span>Login individual</span></div><p className="section-copy">Cada plataforma abre em uma aba própria para você entrar com sua conta. O VagaCerta não compartilha senhas nem cookies entre usuários.</p><div className="integration-grid"><article><div className="integration-logo linkedin">in</div><div><strong>LinkedIn</strong><small>Busca de vagas e candidatura assistida</small></div><a href="https://www.linkedin.com/login" target="_blank" rel="noreferrer">Abrir e conectar</a></article><article><div className="integration-logo gupy">G</div><div><strong>Gupy</strong><small>Portal de vagas e currículo do candidato</small></div><a href="https://login.gupy.io/candidates/signin" target="_blank" rel="noreferrer">Abrir e conectar</a></article></div><p className="helper">Depois de entrar, volte a “Buscar vagas” e abra os resultados da plataforma desejada.</p></section>

    <section className="workspace-card" id="candidaturas"><div className="section-heading"><div><span className="eyebrow">ACOMPANHAMENTO</span><h2>Minhas candidaturas</h2></div><span>{applications.length} registrada(s)</span></div><form className="application-form" onSubmit={addApplication}><input name="company" required placeholder="Empresa" /><input name="role" required placeholder="Cargo" /><select name="platform" defaultValue="LINKEDIN"><option>LINKEDIN</option><option>GUPY</option><option>OUTRO</option></select><input name="externalUrl" type="url" placeholder="Link (opcional)" /><button className="primary-button" type="submit">Registrar</button></form><div className="record-list" id="historico">{applications.length ? applications.map(item => <div className="record application-record" key={item.id}><div className="company-logo">{item.company[0]}</div><div><strong>{item.role}</strong><small>{item.company} · {item.platform}</small></div><select aria-label={`Status de ${item.role}`} value={item.status} onChange={e => updateStatus(item.id, e.target.value)}><option value="DRAFT">Rascunho</option><option value="SENT">Enviada</option><option value="IN_REVIEW">Em análise</option><option value="INTERVIEW">Entrevista</option><option value="REJECTED">Encerrada</option></select>{item.externalUrl && <a href={item.externalUrl} target="_blank" rel="noreferrer">Abrir vaga</a>}</div>) : <p className="empty">Registre sua primeira candidatura para acompanhar o processo.</p>}</div></section>

    <section className="workspace-card" id="configuracoes"><div className="section-heading"><div><span className="eyebrow">SUA CONTA</span><h2>Configurações</h2></div></div><div className="settings-grid"><div><strong>Dados profissionais</strong><p>Atualize profissão, objetivos, competências e disponibilidade.</p><a href="#perfil">Editar perfil</a></div><div><strong>Currículo principal</strong><p>Envie a versão que será usada nas candidaturas.</p><a href="#curriculo">Gerenciar currículos</a></div><div><strong>Plataformas</strong><p>Abra suas contas individuais do LinkedIn e da Gupy.</p><a href="#integracoes">Configurar conexões</a></div></div></section>

    <section className="privacy-card" id="privacidade"><strong>Privacidade e isolamento</strong><p>Todos os registros são associados à identidade da conta conectada. O sistema não aceita um identificador de usuário enviado pela tela para acessar dados de outra pessoa.</p></section>
  </>;
}
